### ISSUE TITLE
Doesn't work in 0.4.59-cae9ef1

### ISSUE THREAD

**Issue by arlo-j** [edipox/elementary-nylas#5]
Tried installing + restarting, themes show up but don't change the actual appearance.

**Comment by edipox** [comment]
Thank you for reporting. I'll take a look

**Comment by edipox** [comment]
Hi @arlo-j I've just tested with the 0.4.59-cae9ef1 and it worked perfectly for me, I just had to install each theme separately

**Comment by a-rock-lobster** [comment]
Theme looks great, but I am encountering the same problem. Installing both sepertately is successful, but does not actually apply any aethetics changes.

**Comment by edipox** [comment]
@a2fingerSalute Thanks for reporting! 
I just tried the latest Nylas Mail release for linux from its github project but couldn't get it to work properly. So I'll wait for the official download for linux to try to reproduce & fix any bug

**Comment by edipox** [comment]
I just tried with N1-1.5.0 and it works. The difference with the default theme is subtle comparing with ElementaryFull: the buttons are not that fat,  there are some extra gradients, and the side panel is darker. So maybe the changes are very minimal and that's why some of you are finding it hard to note some difference. I'm closing this issue for now. Please let me know if you have any update about this
